service:
  name: backend

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  profile: serverless
  runtime: nodejs8.10
  stage: dev

functions:
  upcoming_events:
    handler: handler.upcoming_events
    events:
      - http:
          path: events/upcoming
          method: get
          cors: true
