service:
  name: backend

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  apiGatewayCaching:
    enabled: true

provider:
  name: aws
  profile: netlify
  runtime: nodejs8.10
  stage: dev

functions:
  upcomingEvents:
    handler: handler.upcomingEvents
    events:
      - http:
          path: events/upcoming
          method: get
          cors: true
  joinSlack:
    handler: handler.joinSlack
    events:
      - http:
          path: slack
          method: post
          cors: true
