service:
  name: backend

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  apiGatewayCaching:
    enabled: true

provider:
  name: aws
  profile: netlify
  runtime: nodejs8.10
  stage: dev
  environment:
    # environment variables are stored in AWS SSM
    # they can be set like this (with a user with proper permissions):
    # aws ssm put-parameter --profile netlify --name /asg/RECAPTCHA_SECRET_KEY --type String --value foobar
    GOOGLE_CALENDAR_API_KEY: ${ssm:/asg/GOOGLE_CALENDAR_API_KEY}
    GOOGLE_CALENDAR_ID: ${ssm:/asg/GOOGLE_CALENDAR_ID}
    MEETUP_API_KEY: ${ssm:/asg/MEETUP_API_KEY}
    SLACK_JOIN_REQUEST_URL: ${ssm:/asg/SLACK_JOIN_REQUEST_URL}
    RECAPTCHA_SECRET_KEY: ${ssm:/asg/RECAPTCHA_SECRET_KEY}

functions:
  upcomingEvents:
    handler: handler.upcomingEvents
    events:
      - http:
          path: events/upcoming
          method: get
          cors: true
  joinSlack:
    handler: handler.joinSlack
    events:
      - http:
          path: slack
          method: post
          cors: true
