service:
  name: backend

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-api-gateway-caching
  - serverless-offline

custom:
  apiGatewayCaching:
    enabled: true

provider:
  name: aws
  profile: serverless
  runtime: nodejs8.10
  stage: dev

functions:
  upcomingEvents:
    handler: handler.upcomingEvents
    events:
      - http:
          path: events/upcoming
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 900 # 15 mins
  joinSlack:
    handler: handler.joinSlack
    events:
      - http:
          path: slack
          method: post
          cors: true
          caching:
            enabled: false
